baseurl = "https://tzachs.github.io/"
languageCode = "en-us"
title = "Tzach Solomon's Blog"
theme = "hugo-theme-geppaku"
googleAnalytics = "UA-86794215-1"
disqusShortname = "tzachs"
pygmentsStyle = "native"
newContentEditor = "vi"
